### ISSUE TITLE
Native load path not injected with latest nixpkgs changes

### ISSUE THREAD

**Issue by terlar** [emacs-twist/twist.nix#120]
Recently this was merged: https://github.com/NixOS/nixpkgs/pull/235859

I think this affects the wrapper:
https://github.com/emacs-twist/twist.nix/blob/82cb3be3b1e6c9a88729a5e2951f99d3e55ad9c9/pkgs/emacs/wrapper.nix#L21

Probably a less breaking change from this change would be to still have this attribute propagated on the Emacs derivation as well not only in the input.

**Comment by akirak** [comment]
Thank you for reporting this issue. If #121 resolves your issue, I will merge it quickly.
