### ISSUE TITLE
How to tackle issue with commits seemingly "disappearing" from ELPA

### ISSUE THREAD

**Issue by terlar** [emacs-twist/twist.nix#159]
Hello, I am sorry to raise this here as it is per se not an issue with twist.nix. However I figured you might have run into the same thing and found a solution. Or perhaps there is some weird thing making me run into this but not others.

The issue is with tracking the flake input `git+https://git.savannah.gnu.org/git/emacs/elpa.git?ref=main`. I have builds working at some revision and next time I try to re-run it, it fails with this kind of message:

```
       error: Cannot find Git revision 'd5ea227a3729357b6c4c09bd033db9445fa34048' in ref 'main' of repository 'https://git.savannah.gnu.org/git/emacs/elpa.git'! Please make sure that the rev exists on the ref you've specified or add allRefs = true; to fetchGit.
```

If I search the ELPA git repo, I can find the commit:
https://git.savannah.gnu.org/gitweb/?p=emacs/elpa.git;a=commit;h=d5ea227a3729357b6c4c09bd033db9445fa34048

It also seems to still be associated with the main branch (`* elpa-packages (window-tool-bar): New core package`):
https://git.savannah.gnu.org/gitweb/?p=emacs/elpa.git;a=shortlog;h=refs/heads/main

I only see this behavior with ELPA and it is causing failures for pipelines that worked in the past and only way I found to move forward was to update the input, but it keeps happening.

Feel free to close, in the meantime I will keep investigating...

**Comment by terlar** [comment]
I guess it is this one...
https://github.com/NixOS/nix/issues/10431

Closing.

**Comment by akirak** [comment]
Thank you for reporting this issue. Actually, I am frequently seeing the error, and your information is helpful.

**Comment by terlar** [comment]
Yes, then I'm not alone. It was starting to get really annoying. I reverted back to using nix 2.18.2 for my repos and that solved this issue.

Another semi related issue that I ran into today as well when this issue was solved was that previous ELPA packages from the archive.lock was pulled. E.g. csv-mode was updated from 1.23 to 1.24. Unfortunately the URL to 1.23 did not exist any more so I was forced to update if I wanted my configuration to work.

Quite annoying with sources disappearing because it breaks the reproducibility.

**Comment by akirak** [comment]
> Unfortunately the URL to 1.23 did not exist any more so I was forced to update if I wanted my configuration to work.

Yes, I have the same issue. I don't come up with a solution right now. I have filed #160. If you have an idea, feel free to comment on it. Thank you for your contribution to this project.

**Comment by akirak** [comment]
@terlar I have set up mirrors for the ELPA repositories: @elpa-mirrors. You can use these as a drop-in replacement for the upstream ones like this: https://github.com/akirak/emacs-config/commit/9c18de0ded652d198c9650e764c2d922a8246874
