### ISSUE TITLE
Breaking change in latest Emacs version for native compilation

### ISSUE THREAD

**Issue by terlar** [emacs-twist/twist.nix#161]
The usage of `comp-async-runnings`:
https://github.com/emacs-twist/twist.nix/blob/master/pkgs/emacs/build/comp-native.el#L17

Which apparently is a private function will break after this commit:
https://github.com/emacs-mirror/emacs/commit/fd61cf3976c1c24b5a58923f6520f88db060cacd

Not sure what to do, if just using the private function or if it needs a new solution.

**Comment by akirak** [comment]
@terlar Thank you for reporting this issue. There have been a number of updates in `comp-native.el` since I wrote this library. I will check it out soon.
