### ISSUE TITLE
Documentation on native-comp

### ISSUE THREAD

**Issue by 9glenda** [emacs-twist/twist.nix#163]
I am a bit confused on native-comp support.
Could you provide documentation on the state of nativ-comp support in twist.nix?

It would be really nice to be able to compile all packages using native-comp.

**Comment by akirak** [comment]
Hello, native compilation of Emacs Lisp packages is supported and enabled by default. Twist provides a wrapper for loading the Emacs environment, which adds the native libraries [here](https://github.com/emacs-twist/twist.nix/blob/cdaba19db1af13fb8573db7f1f4fe8d3a69c92cb/pkgs/emacs/wrapper.nix#L183).

If you don't want to use the wrapper, you have to somehow configure your Emacs environment to load the native libraries in Nix. @terlar has a working configuration with native compilation enabled in [this file](https://github.com/terlar/emacs-config/blob/main/default.nix).
